# Generated by Django 5.2.8 on 2025-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SevaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='seva/')),
                ('description', models.TextField(blank=True, null=True)),
                ('order_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
